package com.parkflow.mall.reservation.service;

import com.parkflow.mall.reservation.dto.*;
import com.parkflow.mall.reservation.model.*;
import com.parkflow.mall.reservation.repository.ReservationRepository;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service public class ReservationService {
 private final ReservationRepository repository; private final int motorbikeCapacity; private final int carCapacity; private final int holdMinutes; private final SecureRandom random=new SecureRandom();
 public ReservationService(ReservationRepository repository,@Value("${app.motorbike-capacity:20}") int motorbikeCapacity,@Value("${app.car-capacity:10}") int carCapacity,@Value("${app.default-hold-minutes:60}") int holdMinutes){this.repository=repository;this.motorbikeCapacity=motorbikeCapacity;this.carCapacity=carCapacity;this.holdMinutes=holdMinutes;}
 public synchronized ReservationResponse create(CreateReservationRequest request){ expireStale(); if(request==null||blank(request.vehiclePlate())) bad("vehiclePlate is required"); if(request.vehicleType()==null) bad("vehicleType is required"); if(request.reservedFrom()==null||request.reservedUntil()==null||!request.reservedUntil().isAfter(request.reservedFrom())) bad("reservedUntil must be after reservedFrom"); if(request.reservedFrom().isBefore(Instant.now().minusSeconds(300))) bad("reservedFrom cannot be too far in the past"); String plate=normalize(request.vehiclePlate()); if(repository.hasActivePlate(plate)) conflict("ACTIVE_RESERVATION_EXISTS"); if(repository.activeCountByVehicleType(request.vehicleType())>=capacity(request.vehicleType())) conflict("RESERVATION_CAPACITY_FULL"); Instant now=Instant.now(); Instant expiresAt=request.reservedUntil().isBefore(now.plusSeconds((long)holdMinutes*60))?request.reservedUntil():now.plusSeconds((long)holdMinutes*60); Reservation r=new Reservation(UUID.randomUUID().toString(),code(),request.vehiclePlate().trim(),plate,request.vehicleType(),request.customerName(),request.customerPhone(),request.reservedFrom(),request.reservedUntil(),expiresAt,ReservationStatus.RESERVED,now,null,null,null,null,null); repository.save(r); return response(r,"Reservation created successfully."); }
 public synchronized ReservationResponse get(String code){ expireStale(); return response(require(code),null); }
 public synchronized ReservationResponse cancel(String code,CancelReservationRequest request){ Reservation r=require(code); expireIfNeeded(r); r=require(code); if(r.status()==ReservationStatus.CANCELLED) return response(r,"Reservation cancelled successfully."); if(r.status()!=ReservationStatus.RESERVED) conflict("Reservation cannot be cancelled in its current status"); Reservation updated=new Reservation(r.id(),r.reservationCode(),r.vehiclePlate(),r.normalizedVehiclePlate(),r.vehicleType(),r.customerName(),r.customerPhone(),r.reservedFrom(),r.reservedUntil(),r.expiresAt(),ReservationStatus.CANCELLED,r.createdAt(),Instant.now(),request==null?null:request.reason(),null,null,null); repository.save(updated); return response(updated,"Reservation cancelled successfully."); }
 public synchronized List<ReservationResponse> list(String status,String vehiclePlate){ expireStale(); ReservationStatus wanted=null; if(!blank(status))try{wanted=ReservationStatus.valueOf(status.trim().toUpperCase(Locale.ROOT));}catch(IllegalArgumentException e){bad("Unknown reservation status");} String plate=blank(vehiclePlate)?null:normalize(vehiclePlate); ReservationStatus finalWanted=wanted; return repository.findAll().stream().filter(r->finalWanted==null||r.status()==finalWanted).filter(r->plate==null||r.normalizedVehiclePlate().equals(plate)).map(r->response(r,null)).toList(); }
 public synchronized ExpireReservationsResponse expire(){ return new ExpireReservationsResponse(expireStale(),"Expired stale reservations."); }
 public synchronized ReservationResponse consume(String code,ConsumeReservationRequest request){ if(request==null||blank(request.vehiclePlate())||request.vehicleType()==null||blank(request.parkingSessionId())||blank(request.checkInRequestId())) bad("vehiclePlate, vehicleType, parkingSessionId and checkInRequestId are required"); Reservation r=require(code); expireIfNeeded(r); r=require(code); if(r.status()==ReservationStatus.CONSUMED){if(request.checkInRequestId().equals(r.consumeRequestId()))return response(r,"Reservation already consumed for this check-in."); conflict("Reservation has already been consumed");} if(r.status()!=ReservationStatus.RESERVED) conflict("Reservation is not available for check-in"); if(!r.normalizedVehiclePlate().equals(normalize(request.vehiclePlate()))) conflict("Reservation plate does not match check-in plate"); if(r.vehicleType()!=request.vehicleType()) conflict("Reservation vehicle type does not match"); Instant now=Instant.now(); Reservation updated=new Reservation(r.id(),r.reservationCode(),r.vehiclePlate(),r.normalizedVehiclePlate(),r.vehicleType(),r.customerName(),r.customerPhone(),r.reservedFrom(),r.reservedUntil(),r.expiresAt(),ReservationStatus.CONSUMED,r.createdAt(),null,null,now,request.parkingSessionId(),request.checkInRequestId()); repository.save(updated); return response(updated,"Reservation consumed successfully."); }
 private int expireStale(){int count=0;for(Reservation r:repository.findAll())if(r.status()==ReservationStatus.RESERVED&&expired(r)){repository.save(new Reservation(r.id(),r.reservationCode(),r.vehiclePlate(),r.normalizedVehiclePlate(),r.vehicleType(),r.customerName(),r.customerPhone(),r.reservedFrom(),r.reservedUntil(),r.expiresAt(),ReservationStatus.EXPIRED,r.createdAt(),null,null,null,null,null));count++;}return count;}
 private void expireIfNeeded(Reservation r){if(r.status()==ReservationStatus.RESERVED&&expired(r))expireStale();}
 private boolean expired(Reservation r){Instant now=Instant.now();return !now.isBefore(r.reservedUntil())||!now.isBefore(r.expiresAt());}
 private Reservation require(String code){return repository.findByCode(code).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Reservation not found"));}
 private ReservationResponse response(Reservation r,String message){return new ReservationResponse(r.id(),r.reservationCode(),r.vehiclePlate(),r.vehicleType(),r.reservedFrom(),r.reservedUntil(),r.expiresAt(),r.status(),message);}
 private int capacity(VehicleType type){return type==VehicleType.CAR?carCapacity:motorbikeCapacity;} private String code(){byte[] b=new byte[18];random.nextBytes(b);return "RSV-"+Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String normalize(String p){return p.replaceAll("[^A-Za-z0-9]","").toUpperCase(Locale.ROOT);} private boolean blank(String s){return s==null||s.isBlank();} private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private void conflict(String m){throw new ResponseStatusException(HttpStatus.CONFLICT,m);}
}
