package com.parkflow.mall.payment.service;
import com.parkflow.mall.payment.dto.PaymentDtos.*; import com.parkflow.mall.payment.model.*; import com.parkflow.mall.payment.repository.*;
import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.client.*; import org.springframework.web.server.ResponseStatusException;
@Service public class PaymentService {
 private final PaymentOrderRepository orders; private final InMemoryIdempotencyStore idempotency; private final RestTemplate rest; private final String parkingUrl, internalToken, mode; private final long ttl;
 public PaymentService(PaymentOrderRepository o,InMemoryIdempotencyStore i,RestTemplate r,@Value("${app.parking-base-url}") String p,@Value("${app.internal-service-token}") String t,@Value("${app.payment-mode}") String m,@Value("${app.order-ttl-minutes}") long ttl){orders=o;idempotency=i;rest=r;parkingUrl=p;internalToken=t;mode=m;this.ttl=ttl;}
 public OrderResponse create(CreateOrderRequest req,String key){ if(req==null||req.targetType()!=PaymentTargetType.PARKING_SESSION||blank(req.lookupToken())||blank(req.targetId())) throw bad("Valid PARKING_SESSION target and lookupToken are required"); if(key!=null&&!key.isBlank()){var old=orders.findByCreationKey(key);if(old.isPresent())return response(old.get());} Ticket ticket=ticket(req.lookupToken()); if(!req.targetId().equals(ticket.sessionId))throw bad("targetId does not match lookup token"); if("PAID".equals(ticket.paymentStatus)) throw new ResponseStatusException(HttpStatus.CONFLICT,"Parking session is already paid"); if(!List.of("ACTIVE","PENDING_PAYMENT").contains(ticket.status))throw bad("Parking session is not payable"); PaymentOrder order=new PaymentOrder(UUID.randomUUID().toString(),"PFPAY-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(),req.targetType(),req.targetId(),ticket.finalFee,"VND",PaymentStatus.PENDING,Instant.now(),Instant.now().plus(Duration.ofMinutes(ttl)),null,true,key); return response(orders.save(order)); }
 public OrderResponse get(String id){return response(find(id));}
 public SimulationResponse simulate(SimulateRequest req,String key){ if(!"SIMULATION".equalsIgnoreCase(mode))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Payment simulation is disabled"); if(blank(key))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Idempotency-Key is required"); String prior=idempotency.get(key); if(prior!=null)return simulation(find(prior),"UPDATED"); PaymentOrder order=find(req.paymentOrderId()); if(order.status()==PaymentStatus.PAID){idempotency.putIfAbsent(key,order.id());return simulation(order,"UPDATED");} if(!order.paymentCode().equals(req.paymentCode())||order.amount()!=req.amount()){PaymentOrder mismatch=new PaymentOrder(order.id(),order.paymentCode(),order.targetType(),order.targetId(),order.amount(),order.currency(),PaymentStatus.MISMATCHED,order.createdAt(),order.expiresAt(),null,order.simulationMode(),order.creationIdempotencyKey());orders.save(mismatch);throw new ResponseStatusException(HttpStatus.CONFLICT,"Payment code or amount mismatch");} Instant paid=Instant.now(); PaymentOrder paidOrder=new PaymentOrder(order.id(),order.paymentCode(),order.targetType(),order.targetId(),order.amount(),order.currency(),PaymentStatus.PAID,order.createdAt(),order.expiresAt(),paid,order.simulationMode(),order.creationIdempotencyKey()); String parking="UPDATED"; try{ HttpHeaders h=new HttpHeaders();h.set("X-Internal-Service-Token",internalToken);h.setContentType(MediaType.APPLICATION_JSON); Map<String,Object> body=Map.of("paymentOrderId",order.id(),"paymentStatus","PAID","amountPaid",order.amount(),"paidAt",paid.toString());rest.exchange(parkingUrl+"/internal/parking/sessions/"+order.targetId()+"/payment-status",HttpMethod.POST,new HttpEntity<>(body,h),String.class);}catch(RestClientException ex){parking="PENDING_RECONCILIATION";paidOrder=new PaymentOrder(paidOrder.id(),paidOrder.paymentCode(),paidOrder.targetType(),paidOrder.targetId(),paidOrder.amount(),paidOrder.currency(),PaymentStatus.PENDING_RECONCILIATION,paidOrder.createdAt(),paidOrder.expiresAt(),paid,paidOrder.simulationMode(),paidOrder.creationIdempotencyKey());} orders.save(paidOrder);idempotency.putIfAbsent(key,paidOrder.id());return simulation(paidOrder,parking); }
 private Ticket ticket(String token){try{return rest.getForObject(parkingUrl+"/api/public/tickets/"+token,Ticket.class);}catch(RestClientException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Ticket not found");}}
 private PaymentOrder find(String id){return orders.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Payment order not found"));} private OrderResponse response(PaymentOrder o){return new OrderResponse(o.id(),o.targetType(),o.targetId(),o.paymentCode(),o.amount(),o.currency(),o.status(),o.expiresAt(),o.paidAt(),o.simulationMode());} private SimulationResponse simulation(PaymentOrder o,String parking){return new SimulationResponse(o.id(),o.status(),o.paidAt(),o.targetType(),o.targetId(),parking);} private boolean blank(String s){return s==null||s.isBlank();} private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);} static class Ticket {public String sessionId,status,paymentStatus;public long finalFee;}
}
